services:
  - type: web
    name: chatbot-aniya
    env: python
    buildCommand: |
      cd frontend && npm install && npm run build && cd ..
    startCommand: uvicorn backend.main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: SUPABASE_URL
        value: your_supabase_url
      - key: SUPABASE_KEY
        value: your_supabase_key